### ISSUE TITLE
great job, can i ask where to download "kolors-unet.safetenors",tks

### ISSUE THREAD

**Issue by BNP1111** [MinusZoneAI/ComfyUI-Kolors-MZ#1]
great job, can i ask where to download "kolors-unet.safetenors",tks

**Comment by wailovet** [comment]
https://huggingface.co/Kwai-Kolors/Kolors/blob/main/unet/diffusion_pytorch_model.fp16.safetensors

**Comment by away94away** [comment]
我按教程 下载的模型 但是能显示 能选择这个unet模型 一跑 就报错
Error occurred when executing MZ_KolorsUNETLoader:

module 'comfy.model_detection' has no attribute 'unet_prefix_from_state_dict'
请教怎么解决？

**Comment by Sheldongg** [comment]
> 我按教程 下载的模型 但是能显示 能选择这个unet模型 一跑 就报错 Error occurred when executing MZ_KolorsUNETLoader:
> 
> module 'comfy.model_detection' has no attribute 'unet_prefix_from_state_dict' 请教怎么解决？

同样的报错

**Comment by wailovet** [comment]
> > 我按教程 下载的模型 但是能显示 能选择这个unet模型 一跑 就报错 Error occurred when executing MZ_KolorsUNETLoader:
> > module 'comfy.model_detection' has no attribute 'unet_prefix_from_state_dict' 请教怎么解决？
> 
> 同样的报错

使用的是最新版本的comfyui吗

**Comment by Sheldongg** [comment]
> > > 我按教程 下载的模型 但是能显示 能选择这个unet模型 一跑 就报错 Error occurred when executing MZ_KolorsUNETLoader:
> > > module 'comfy.model_detection' has no attribute 'unet_prefix_from_state_dict' 请教怎么解决？
> > 
> > 
> > 同样的报错
> 
> 使用的是最新版本的comfyui吗

哈哈 感谢 是的 更新完就好了

**Comment by wailovet** [comment]
> 我按教程 下载的模型 但是能显示 能选择这个unet模型 一跑 就报错 Error occurred when executing MZ_KolorsUNETLoader:
> 
> module 'comfy.model_detection' has no attribute 'unet_prefix_from_state_dict' 请教怎么解决？

 更新ComfyUI到最新版本
