### ISSUE TITLE
Error occurred when executing MZ_ChatGLM3Loader:  name 'round_up' is not defined

### ISSUE THREAD

**Issue by KANKANYANGKANKAN** [MinusZoneAI/ComfyUI-Kolors-MZ#11]
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\__init__.py", line 64, in load_chatglm3
return mz_kolors_core.MZ_ChatGLM3Loader_call(kwargs)
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 113, in MZ_ChatGLM3Loader_call
text_encoder.quantize(4)
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\modeling_chatglm.py", line 852, in quantize
quantize(self.encoder, weight_bit_width)
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 155, in quantize
layer.self_attention.query_key_value = QuantizedLinear(
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 139, in __init__
self.weight = compress_int4_weight(self.weight)
File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 76, in compress_int4_weight
blockDim = (min(round_up(m, 32), 1024), 1, 1)
![QQ图片20240712160206](https://github.com/user-attachments/assets/941a3460-5118-4080-8afc-e8036cf8d650)

**Comment by wailovet** [comment]
Try the 8bit version

**Comment by wailovet** [comment]
> File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ__init__.py", line 64, in load_chatglm3 return mz_kolors_core.MZ_ChatGLM3Loader_call(kwargs) File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 113, in MZ_ChatGLM3Loader_call text_encoder.quantize(4) File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\modeling_chatglm.py", line 852, in quantize quantize(self.encoder, weight_bit_width) File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 155, in quantize layer.self_attention.query_key_value = QuantizedLinear( File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 139, in **init** self.weight = compress_int4_weight(self.weight) File "D:\ComfyUI_aaki\ComfyUI-aki-v1.37\ComfyUI-aki-v1.37\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 76, in compress_int4_weight blockDim = (min(round_up(m, 32), 1024), 1, 1) ![QQ图片20240712160206](https://private-user-images.githubusercontent.com/169335809/348174473-941a3460-5118-4080-8afc-e8036cf8d650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MDE2MzIsIm5iZiI6MTcyMDgwMTMzMiwicGF0aCI6Ii8xNjkzMzU4MDkvMzQ4MTc0NDczLTk0MWEzNDYwLTUxMTgtNDA4MC04YWZjLWU4MDM2Y2Y4ZDY1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxNjIyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2Y3M2I0Nzg2OWYzMTliMDA2NjliMGY5MGE3ZjZjYzBlOWVhZWUzMDk5ZmJmOTJlZTE3NjdlOGQxMmYxNTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G3CCMGsgnMTVVONwVzAQgysmxMPAy3MtuCMa7yueoZ8)

reference : https://github.com/THUDM/ChatGLM2-6B/issues/272#issuecomment-1632164243

Quantization rely on cpm_kernels. Install it by:
```
pip install cpm_kernels
```
