### ISSUE TITLE
Error occurred when executing KSampler:  shape '[1280, 5632]' is invalid for input of size 3604480

### ISSUE THREAD

**Issue by Serge108** [MinusZoneAI/ComfyUI-Kolors-MZ#15]
Error occurred when executing KSampler:
shape '[1280, 5632]' is invalid for input of size 3604480

while using midas depth map

**Comment by wailovet** [comment]
Are you using ControlLora, update to the latest code, use MZ_ KolorsControlNetPatch node and try again

![image](https://github.com/user-attachments/assets/8d5cb392-3d8e-496f-8e75-7384b6bdd708)
