### ISSUE TITLE
Error occurred when executing KSampler:

### ISSUE THREAD

**Issue by tianshanxin** [MinusZoneAI/ComfyUI-Kolors-MZ#19]
Error occurred when executing KSampler:

mat1 and mat2 must have the same dtype, but got Half and Float

File "D:\ComfyUI-ainewsto\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI-ainewsto\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI-ainewsto\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI-ainewsto\ComfyUI\nodes.py", line 1373, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI-ainewsto\ComfyUI\nodes.py", line 1343, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI-ainewsto\ComfyUI\custom_nodes\Comfyui-StableSR\nodes.py", line 75, in hook_sample
return original_sample(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI-ainewsto\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
raise e
The plugin is already up-to-date.Workflows are also in accordance with your latest.But the error is still reported.

**Comment by wailovet** [comment]
Can you provide the workflow?

**Comment by tianshanxin** [comment]
<img width="1884" alt="MiMouseShot20240714145557" src="https://github.com/user-attachments/assets/59ea9e9b-0708-404b-bcbd-ecbf63079046">

**Comment by tianshanxin** [comment]
[Uploading kolors controlnet.json…]()

**Comment by tianshanxin** [comment]
Workflow is what you are in the plugin case.

**Comment by tianshanxin** [comment]
I looked at several different comfyui nvironments,It's the same Error reported.

**Comment by wailovet** [comment]
> I looked at several different comfyui nvironments,It's the same Error reported.

I can't reproduce this bug, this might have something to do with the model I downloaded.
I'll try to fix it for now, can update it and try again.

**Comment by tianshanxin** [comment]
Is it a re-download model?

**Comment by wailovet** [comment]
> Is it a re-download model?

No, update the node

**Comment by tianshanxin** [comment]
The node has been updated, But still same error.

**Comment by wailovet** [comment]
> The node has been updated, But still same error.

Does your comfyui launched args contain --fp16-unet?

**Comment by tianshanxin** [comment]
Yes, it should be included.I switched to 8bit model,It's also the same mistake.

**Comment by wailovet** [comment]
> The node has been updated, But still same error.

I reproduced this bug --fp16-unet, you update the node again and try to see if it works.

**Comment by tianshanxin** [comment]
<img width="882" alt="MiMouseShot20240714154321" src="https://github.com/user-attachments/assets/bbce767d-dc62-40e4-b9be-e158b0d610fc">

**Comment by tianshanxin** [comment]
Yeah, thanks, I'll try it.

**Comment by tianshanxin** [comment]
Thank you very much, the problem has been solved,
