### ISSUE TITLE
Can you load other large language models, such as Florence-2-large, the computer configuration is not enough, GLM3 this run burst video memory!

### ISSUE THREAD

**Issue by jokero3answer** [MinusZoneAI/ComfyUI-Kolors-MZ#24]

**Comment by jokero3answer** [comment]
@wailovet Thank you

**Comment by jokero3answer** [comment]
![image](https://github.com/user-attachments/assets/324735ff-6621-44c3-a7d7-481db28d6c61)

**Comment by wailovet** [comment]
Try using a 4bit/8bit model 
[https://huggingface.co/Kijai/ChatGLM3-safetensors/](https://huggingface.co/Kijai/ChatGLM3-safetensors/blob/main/chatglm3-fp16.safetensors)

**Comment by jokero3answer** [comment]
![image](https://github.com/user-attachments/assets/fb0cf2c7-c210-44f5-a3b5-2f6018edcae4)
Thank you for your reply, is it still necessary to download this encoder and where do I need to put it, I saw it mentioned in another plugin@wailovet

**Comment by wailovet** [comment]
> ![image](https://private-user-images.githubusercontent.com/130854108/349020713-fb0cf2c7-c210-44f5-a3b5-2f6018edcae4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjQxNzcsIm5iZiI6MTcyMTEyMzg3NywicGF0aCI6Ii8xMzA4NTQxMDgvMzQ5MDIwNzEzLWZiMGNmMmM3LWMyMTAtNDRmNS1hM2I1LTJmNjAxOGVkY2FlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwOTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTc4N2IzOWE0NmI4MjdmYzk3YmZmOWIxZTA1M2MyMzU5YzMwNmNiN2U3Y2FmNGVmYmE1NjljZTk4ZDU2OTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CB1rgV6NtBd26PGS3BSYj-9XQpDf2QnZdQsGskymUVI) Thank you for your reply, is it still necessary to download this encoder and where do I need to put it, I saw it mentioned in another plugin@wailovet

If you use the model in Kijai/ChatGLM3-safetensors you don't need Kolorstext_encoder
