### ISSUE TITLE
请问下【删除自动兼容ControlNet, 新增MZ_KolorsControlNetPatch节点】的原因是啥呀

### ISSUE THREAD

**Issue by WainWong** [MinusZoneAI/ComfyUI-Kolors-MZ#27]
请问这个新增的节点是可以有更好的效果吗？我之前主要是使用Adv Controlnet，那个可以调节起始和结束步骤，还挺不错的

**Comment by wailovet** [comment]
> 请问这个新增的节点是可以有更好的效果吗？我之前主要是使用Adv Controlnet，那个可以调节起始和结束步骤，还挺不错的

不影响继续使用Adv Controlnet,  使用MZ_KolorsControlNetPatch串联上Adv Controlnet就行
之前的实现方式通过全局重写comfyui类和方法实现,如果其他节点也用了同样的方式可能不兼容
目前实现方式把对对象的改动限制在节点的运行范围内

**Comment by WainWong** [comment]
噢噢了解了感谢
