### ISSUE TITLE
Error occurred when executing MZ_KolorsUNETLoader:  Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by gaoshuai1002** [MinusZoneAI/ComfyUI-Kolors-MZ#28]
![38b56f45-7768-44ba-83c7-a82c3b785011](https://github.com/user-attachments/assets/eb99e277-d4d6-4bf8-9f27-d321cbc17e3f)
![aaa](https://github.com/user-attachments/assets/b421e0fe-e545-450c-be77-d31afc12a1e7)

**Comment by wailovet** [comment]
Check the integrity of the model file, maybe the downloaded model file is abnormal.

**Comment by YuenSzeHong** [comment]
well, I have redownloaded the model from the given link, but the error persists

**Comment by YuenSzeHong** [comment]
you guys should update your docs, users should replace `blob` with `resolve` when downloading the models with curl or wget on the URLs given int the docs which most users docs in Linux environments.

**Comment by wailovet** [comment]
> you guys should update your docs, users should replace `blob` with `resolve` when downloading the models with curl or wget on the URLs given in the docs which most users docs in Linux environments.

I agree!
