### ISSUE TITLE
Error occurred when executing MZ_KolorsUNETLoader:  cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by gaoshuai1002** [MinusZoneAI/ComfyUI-Kolors-MZ#30]
![111fe60a-d0c7-4efc-96d9-603e962410f5](https://github.com/user-attachments/assets/3cdc4284-55db-4c2a-b380-a9ce06ee5d71)

**Comment by wailovet** [comment]
Use example\workflow.png if there is the same error?

**Comment by gaoshuai1002** [comment]
> Use example\workflow.png if there is the same error?

是的 YES

**Comment by wailovet** [comment]
> > Use example\workflow.png if there is the same error?
> 
> 是的 YES

要不你加下微信我给你看看吧

**Comment by datou424** [comment]
i have the same error
