### ISSUE TITLE
mac运行新更新的ipa流程时 环境会直接崩溃

### ISSUE THREAD

**Issue by yiwangsimple** [MinusZoneAI/ComfyUI-Kolors-MZ#35]
psFileLoc): /AppleInternal/Library/BuildRoots/91a344b1-f985-11ee-b563-fe8bc7981bff/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":233:0)): error: input types 'tensor<2x256x2048xf16>' and 'tensor<2048xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
Abort trap: 6
(comfyui) weiweideMacBook-Pro:comfyui weiwei$ /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by wailovet** [comment]
Mac的支持暂时还有问题

**Comment by yiwangsimple** [comment]
> same issue from my M1 pro
> 
> loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/91a344b1-f985-11ee-b563-fe8bc7981bff/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":233:0)): error: input types 'tensor<2x256x2048xf16>' and 'tensor<2048xf32>' are not broadcast compatible LLVM ERROR: Failed to infer result type(s).

I've optimized the nodes, go directly to my homepage to find them

**Comment by yixian3500** [comment]
> > same issue from my M1 pro
> > loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/91a344b1-f985-11ee-b563-fe8bc7981bff/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":233:0)): error: input types 'tensor<2x256x2048xf16>' and 'tensor<2048xf32>' are not broadcast compatible LLVM ERROR: Failed to infer result type(s).
> 
> I've optimized the nodes, go directly to my homepage to find them

nice job man! got it, thanks !!!
