### ISSUE TITLE
The size of tensor a (257) must match the size of tensor b (577) at non-singleton dimension 1

### ISSUE THREAD

**Issue by paulzhang913** [MinusZoneAI/ComfyUI-Kolors-MZ#38]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
INFO: the IPAdapter reference image is not a square, CLIPImageProcessor will resize and crop it at the center. If the main focus of the picture is not in the middle the result might not be what you are expecting.
!!! Exception during processing!!! The size of tensor a (257) must match the size of tensor b (577) at non-singleton dimension 1
Traceback (most recent call last):
  File "D:\softz\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\softz\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\softz\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\softz\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 758, in apply_ipadapter
    work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args)
  File "D:\softz\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 309, in ipadapter_execute
    img_cond_embeds = encode_image_masked(clipvision, image, batch_size=encode_batch_size)
  File "D:\softz\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 177, in encode_image_masked
    out = clip_vision.model(pixel_values=pixel_values, intermediate_output=-2)
  File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\softz\ComfyUI\comfy\clip_model.py", line 192, in forward
    x = self.vision_model(*args, **kwargs)
  File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\softz\ComfyUI\comfy\clip_model.py", line 178, in forward
    x = self.embeddings(pixel_values)
  File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\softz\ComfyUI\comfy\clip_model.py", line 160, in forward
    return torch.cat([self.class_embedding.to(embeds.device).expand(pixel_values.shape[0], 1, -1), embeds], dim=1) + self.position_embedding.weight.to(embeds.device)
RuntimeError: The size of tensor a (257) must match the size of tensor b (577) at non-singleton dimension 1

**Comment by wailovet** [comment]
Check if you are using the [ip_adapter_plus_general.bin](https://huggingface.co/Kwai-Kolors/Kolors-IP-Adapter-Plus/blob/main/ip_adapter_plus_general.bin) model

**Comment by dogami567** [comment]
Are you using the official workflow? The nodes in that workflow are not mz_'s workflow, IPA's native workflow. If we replace them all with mz_ nodes, everything will be fine

**Comment by wailovet** [comment]
> Are you using the official workflow? The nodes in that workflow are not mz_'s workflow, IPA's native workflow. If we replace them all with mz_ nodes, everything will be fine

I commit a version to ComfyUI_IPAdapter_plus yesterday, it should work normally

**Comment by wailovet** [comment]
> got prompt [rgthree] Using rgthree's optimized recursive execution. INFO: the IPAdapter reference image is not a square, CLIPImageProcessor will resize and crop it at the center. If the main focus of the picture is not in the middle the result might not be what you are expecting. !!! Exception during processing!!! The size of tensor a (257) must match the size of tensor b (577) at non-singleton dimension 1 Traceback (most recent call last): File "D:\softz\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "D:\softz\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "D:\softz\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "D:\softz\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 758, in apply_ipadapter work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args) File "D:\softz\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 309, in ipadapter_execute img_cond_embeds = encode_image_masked(clipvision, image, batch_size=encode_batch_size) File "D:\softz\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 177, in encode_image_masked out = clip_vision.model(pixel_values=pixel_values, intermediate_output=-2) File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "D:\softz\ComfyUI\comfy\clip_model.py", line 192, in forward x = self.vision_model(*args, **kwargs) File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "D:\softz\ComfyUI\comfy\clip_model.py", line 178, in forward x = self.embeddings(pixel_values) File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "D:\softz\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "D:\softz\ComfyUI\comfy\clip_model.py", line 160, in forward return torch.cat([self.class_embedding.to(embeds.device).expand(pixel_values.shape[0], 1, -1), embeds], dim=1) + self.position_embedding.weight.to(embeds.device) RuntimeError: The size of tensor a (257) must match the size of tensor b (577) at non-singleton dimension 1

Is your current ComfyUI_IPAdapter_plus the latest version?

**Comment by dogami567** [comment]
> > Are you using the official workflow? The nodes in that workflow are not mz_'s workflow, IPA's native workflow. If we replace them all with mz_ nodes, everything will be fine
> 
> I commit a version to ComfyUI_IPAdapter_plus yesterday, it should work normally

I am using the example workflow in Git, which generates these errors. After that, replacing all nodes with mz_ nodes solved the problem

**Comment by wailovet** [comment]
> > > Are you using the official workflow? The nodes in that workflow are not mz_'s workflow, IPA's native workflow. If we replace them all with mz_ nodes, everything will be fine
> > 
> > 
> > I commit a version to ComfyUI_IPAdapter_plus yesterday, it should work normally
> 
> I am using the example workflow in Git, which generates these errors. After that, replacing all nodes with mz_ nodes solved the problem

Have you tried the examples/workflow_ipa.png workflow .
This workflow has deprecated the use of mz_ nodes

**Comment by JiangAogo** [comment]
i have the same question and i try to change the nodes of ipadapter, but there have no use:
<img width="865" alt="1" src="https://github.com/user-attachments/assets/31475614-23c0-46d8-a02d-8490f3af31a2">
<img width="1073" alt="2" src="https://github.com/user-attachments/assets/8b58a571-a340-493a-a68c-592b1b350eed">

**Comment by wailovet** [comment]
> i have the same question and i try to change the nodes of ipadapter, but there have no use: <img alt="1" width="865" src="https://private-user-images.githubusercontent.com/163291481/350672584-31475614-23c0-46d8-a02d-8490f3af31a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjIyNjEsIm5iZiI6MTcyMTQ2MTk2MSwicGF0aCI6Ii8xNjMyOTE0ODEvMzUwNjcyNTg0LTMxNDc1NjE0LTIzYzAtNDZkOC1hMDJkLTg0OTBmM2FmMzFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNzUyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Yzk5N2Q3YWU1MTQ2YzZhZThlNTgxM2UxODZmNTE4MDk1YmIyMTY4MjI3MDNiMDkyYWIyY2JjOTNmYzQyZDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TgPrPSFTXmI25ZoNZaI9p5Eyy1Mfnbj2HWOubT_PbPE"> <img alt="2" width="1073" src="https://private-user-images.githubusercontent.com/163291481/350672622-8b58a571-a340-493a-a68c-592b1b350eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjIyNjEsIm5iZiI6MTcyMTQ2MTk2MSwicGF0aCI6Ii8xNjMyOTE0ODEvMzUwNjcyNjIyLThiNThhNTcxLWEzNDAtNDkzYS1hNjhjLTU5MmIxYjM1MGVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNzUyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE3ZDYyODMyZjg0ZDkyMDE1ZGU1ZTY3NTdlNWJkMDVhZWJkZjI2ZGE1ZDUyMDFhODQ4ZDkwNmU1MTY4MjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uIk50bDe-CK_9FYVlDwN-ybazh-s_3Lm4iGJyBd66hc">

You can try to see if this workflow works examples/workflow_ipa_legacy.png ?

**Comment by paulzhang913** [comment]
> ComfyUI_IPAdapter_plus

Thank you, it is because this node has not been updated. There is no problem with the workflow.
