### ISSUE TITLE
KolorsCheckpointLoaderSimple应该用哪个权重？

### ISSUE THREAD

**Issue by botnang** [MinusZoneAI/ComfyUI-Kolors-MZ#57]
ComfyUI-Kolors-MZ\examples\workflow_official_controlnet.png

![image](https://github.com/user-attachments/assets/51c03e25-9fd0-425a-9b22-1038437620c2)
试了这两个模型都提示错误：
RuntimeError: ERROR: Could not detect model type of: E:\AI\models/Stable-diffusion\kolors-.fp16.safetensors

难道是我python环境的问题？但是其他采用KolorsUNETLoader/V2的工作流都能正常运行。

**Comment by botnang** [comment]
![image](https://github.com/user-attachments/assets/3fece811-a069-4e7b-bb6d-25afe5193d68)

**Comment by wailovet** [comment]
用KolorsUnet加载器试试 模型放models/unet中 目前有两个版本在外面  一种是unet类型采用unet加载器一种是放checkpoints文件夹用KolorsCheckpointLoaderSimple加载器的,  你从hug下载的话应该是unet的

**Comment by botnang** [comment]
> 用KolorsUnet加载器试试 模型放models/unet中 目前有两个版本在外面 一种是unet类型采用unet加载器一种是放checkpoints文件夹用KolorsCheckpointLoaderSimple加载器的, 你从hug下载的话应该是unet的

换unetloader解决问题，感谢：）
