### ISSUE TITLE
一个建议，

### ISSUE THREAD

**Issue by BoosterCore** [MinusZoneAI/ComfyUI-Kolors-MZ#68]
这套插件涉及的模型比较多，是否可以考虑在代码中实现对 `extra_model_paths.yaml` 的支持？
主要是现在ComfyUI的生态越来越庞大，各个插件之间的冲突也比较常见，所以有一个需求，就是把所有各种模型统一存放在一个目录中，多个ComfyUI副本指向到该模型目录。这样可以避免模型的重复存放，节省很多磁盘空间。

这个功能我在 AuraSR 项目那边也提了，一番讨论后，作者已经更新并实现了。您可以参考：https://github.com/GreenLandisaLie/AuraSR-ComfyUI/issues/10

您这个项目，我目前测试下来，就只有LLM和insightface这两个目录无法支持 `extra_model_paths.yaml`，其它几个目录都还是原生就支持的。

**Comment by BoosterCore** [comment]
是这个，但我已经将插件升级到最新版，然而LLM目录并不能实现对`extra_model_paths.yaml`的支持，insightface目录也存在这样的问题。

**Comment by wailovet** [comment]
> 是这个，感谢提醒，试了LLM，可以！ 但insightface目录目前好像还不行。

insightface是IPA相关功能的话以[cubiq/ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) 仓库为准,那边已经实现关于kolors的ipa功能

**Comment by BoosterCore** [comment]
Finally, I use `mklink `to solve this issue
