### ISSUE TITLE
模型目录设定问题

### ISSUE THREAD

**Issue by zhangfanpc** [MinusZoneAI/ComfyUI-Kolors-MZ#70]
我已经装好 [/kijai/ComfyUI-KwaiKolorsWrapper]  节点了，并且运行正常。

KwaiKolorsWrappe 调用模型目录在：\sd-ComfyUI\models\diffusers\Kolors 下

但 MZ的节点 好像调用模型路径不是这个，导致模型都是空的。

如何修改 MZ节点的目录呢？

**Comment by wailovet** [comment]
比较简单的 直接把diffusers\Kolors\unet下的模型文件复制到 \sd-ComfyUI\models\unet\下

**Comment by zhangfanpc** [comment]
这样占用好多浪费的空间

**Comment by wailovet** [comment]
> 这样占用好多浪费的空间
你也可以编辑./extra_model_paths.yaml文件,通过自定义目录来使用
![image](https://github.com/user-attachments/assets/6f06495e-605e-4660-8fc5-da4aa6bc867e)

**Comment by zhangfanpc** [comment]
这个会影响 KwaiKolorsWrapper，不知道可以单独设定 MZ节点的目录？

**Comment by wailovet** [comment]
> 这个会影响 KwaiKolorsWrapper，不知道可以单独设定 MZ节点的目录？

这里设定的是unet的额外目录,为什么会影响KwaiKolorsWrapper

**Comment by zhangfanpc** [comment]
![微信截图_20240806115301](https://github.com/user-attachments/assets/1af2ab04-8000-4740-a29a-4d03053212a1)
我的配置是这样的，无法工作。是不是我和 webui 共用了模型？

**Comment by wailovet** [comment]
> ![微信截图_20240806115301](https://private-user-images.githubusercontent.com/12772081/355305789-1af2ab04-8000-4740-a29a-4d03053212a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTkxODQsIm5iZiI6MTcyMjkxODg4NCwicGF0aCI6Ii8xMjc3MjA4MS8zNTUzMDU3ODktMWFmMmFiMDQtODAwMC00NzQwLWEyOWEtNGQwMzA1MzIxMmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA0MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNDJmMjFlMjIzOTcwZWU5MDEyZWRhMzA5ZWNmMmJmNTZjNjIzNWM2MWRmMDVlNjQ1NGQ1OWVlN2VjNGEzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GKoF56IY_mQYI0VUcy2kxIOML0SaHXT_woMJ-EsANBA) 我的配置是这样的，无法工作。是不是我和 webui 共用了模型？

你试一下使用绝对路径

**Comment by zhangfanpc** [comment]
![image](https://github.com/user-attachments/assets/06916612-2468-4e3d-96b2-88ecdae84dbb)
改成绝对路径后，正常了！

**Comment by zhangfanpc** [comment]
多谢，赛博活佛 亲自回复！
