### ISSUE TITLE
GGUF support for text encoder?

### ISSUE THREAD

**Issue by doogyhatts** [MinusZoneAI/ComfyUI-Kolors-MZ#82]
We need a GGUF loader for the ChatGLM3.
https://huggingface.co/mradermacher/chatglm3-6b-GGUF/tree/main

**Comment by liulsg** [comment]
Also needed, but can not find the relevant plug-in support

**Comment by doogyhatts** [comment]
I have moved on to SD3.5.

**Comment by liulsg** [comment]
@doogyhatts 
This is different, flux has average generalization performance in many aspects, but the final details are better. Use KOLOS to perform front and back flux, and then modify the back.
As for the graphics speed of SD3.5, it is the same as Flux, but its drawbacks are similar to XL version.

**Comment by doogyhatts** [comment]
@liulsg I am not sure how that works since I didn't bother too much with Flux. 
What does "front and back flux" mean?
