### ISSUE TITLE
MZ_ChatGLM3 ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'

### ISSUE THREAD

**Issue by leejiang2023** [MinusZoneAI/ComfyUI-Kolors-MZ#84]
MZ_ChatGLM3 ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'pytorch version: 2.4.1+cu124 xformers version: 0.0.28.post1

**Comment by wailovet** [comment]
Could you please paste the complete error message?

**Comment by leejiang2023** [comment]
ChatGLM3编码_V2高级
ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'


# ComfyUI Error Report
## Error Details
- **Node Type:** MZ_ChatGLM3_Advance_V2
- **Exception Type:** TypeError
- **Exception Message:** ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'
## Stack Trace
```
  File "E:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ\__init__.py", line 137, in encode
    return mz_kolors_core.MZ_ChatGLM3TextEncodeV2_call(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 137, in MZ_ChatGLM3TextEncodeV2_call
    prompt_embeds, pooled_output = chatglm3_text_encode(
                                   ^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 34, in chatglm3_text_encode
    text_inputs = tokenizer(
                  ^^^^^^^^^^

  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3025, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3135, in _call_one
    return self.encode_plus(
           ^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3211, in encode_plus
    return self._encode_plus(
           ^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils.py", line 801, in _encode_plus
    return self.prepare_for_model(
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3707, in prepare_for_model
    encoded_inputs = self.pad(
                     ^^^^^^^^^

  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3509, in pad
    encoded_inputs = self._pad(
                     ^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-54-g68bb885
- **Arguments:** E:\ComfyUI\ComfyUI\main.py --auto-launch --preview-method latent2rgb --disable-smart-memory --disable-cuda-malloc --fast
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 4986148800
  - **Torch VRAM Total:** 6811549696
  - **Torch VRAM Free:** 32675776

**Comment by wailovet** [comment]
It seems to be an error in transformers. Do you know the current version number of transformers?

**Comment by leejiang2023** [comment]
![微信图片_20240920085642](https://github.com/user-attachments/assets/a603d9f7-5b6e-4fb1-a8eb-62287bd317c1)
Thank you very much. It was solved after reinstalling transformers. Thank you.

**Comment by ababiya-worku** [comment]
> ![微信图片_20240920085642](https://private-user-images.githubusercontent.com/150128462/369219344-a603d9f7-5b6e-4fb1-a8eb-62287bd317c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDgxMzIsIm5iZiI6MTcyODcwNzgzMiwicGF0aCI6Ii8xNTAxMjg0NjIvMzY5MjE5MzQ0LWE2MDNkOWY3LTViNmUtNGZiMS1hOGViLTYyMjg3YmQzMTdjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjUzZWU0MjBjYmUxNjIzOGQyNzY0NzhkYTdjOTJmM2QwNzNlOWRlODAwMjhjZDhiYjE0YmZhOGM0NWNjZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fm2aPGGCsge0Qfu1xe0irobkFNmi0P2fWry3m4Fblck) Thank you very much. It was solved after reinstalling transformers. Thank you.

PLS HELP ITS NOT WORKING FOR ME, EVEN THOUGH I BOTH DOWNGRADE AND UPGRADE IT

**Comment by wailovet** [comment]
> > ![微信图片_20240920085642](https://private-user-images.githubusercontent.com/150128462/369219344-a603d9f7-5b6e-4fb1-a8eb-62287bd317c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDgxMzIsIm5iZiI6MTcyODcwNzgzMiwicGF0aCI6Ii8xNTAxMjg0NjIvMzY5MjE5MzQ0LWE2MDNkOWY3LTViNmUtNGZiMS1hOGViLTYyMjg3YmQzMTdjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjUzZWU0MjBjYmUxNjIzOGQyNzY0NzhkYTdjOTJmM2QwNzNlOWRlODAwMjhjZDhiYjE0YmZhOGM0NWNjZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fm2aPGGCsge0Qfu1xe0irobkFNmi0P2fWry3m4Fblck) Thank you very much. It was solved after reinstalling transformers. Thank you.
> 
> PLS HELP ITS NOT WORKING FOR ME, EVEN THOUGH I BOTH DOWNGRADE AND UPGRADE IT

 Is it the latest version of ComfyUI-Kolors-MZ?
