### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float

### ISSUE THREAD

**Issue by DarkAlchy** [MinusZoneAI/ComfyUI-Kolors-MZ#9]
I cannot get this to work and I grabbed everything from this:

![image](https://github.com/MinusZoneAI/ComfyUI-Kolors-MZ/assets/10561690/80f01bc2-77ba-4646-a4f0-87ae7e3a3462)

edit:  The full traceback:

!!! Exception during processing!!! mat1 and mat2 must have the same dtype, but got Half and Float
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ\__init__.py", line 90, in encode
    return mz_kolors_core.MZ_ChatGLM3TextEncode_call(kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 147, in MZ_ChatGLM3TextEncode_call
    prompt_embeds = hid_proj(prompt_embeds)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float

**Comment by DarkAlchy** [comment]
Even --force-fp32 did not fix this.

**Comment by wailovet** [comment]
> Even --force-fp32 did not fix this.

Which chatglm model do you use?

**Comment by DarkAlchy** [comment]
> > Even --force-fp32 did not fix this.
> 
> Which chatglm model do you use?

The largest one so the fp16 version.  I did not want the 8bit ot the 4bit since I hate those in my LLMs I have tried in the past and I am not in fp8 mode in Comfy.

**Comment by wailovet** [comment]
> > > Even --force-fp32 did not fix this.
> > 
> > 
> > Which chatglm model do you use?
> 
> The largest one so the fp16 version. I did not want the 8bit or the 4bit versions since I hate those in my LLMs that I have tried in the past, and I am not in fp8 mode in Comfy.

Can you provide a screenshot of the chatglm loader?

**Comment by DarkAlchy** [comment]
You mean the node?
![image](https://github.com/MinusZoneAI/ComfyUI-Kolors-MZ/assets/10561690/97268ef9-4b31-4dd7-91a4-bcb7cf4a1ac5)

**Comment by wailovet** [comment]
> You mean the node? ![image](https://private-user-images.githubusercontent.com/10561690/347896068-97268ef9-4b31-4dd7-91a4-bcb7cf4a1ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjA1MTUsIm5iZiI6MTcyMDcyMDIxNSwicGF0aCI6Ii8xMDU2MTY5MC8zNDc4OTYwNjgtOTcyNjhlZjktNGIzMS00ZGQ3LTkxYTQtYmNiN2NmNGExYWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE3NTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YWRhY2VjZmU5MjFmNTVkOGVhZDFkOWI2MzY2MjYwMzM2NDY4NTQ3N2ZjZjBjZjAwNWNmZjBkNWMyMzBkZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ksxiS9EoglYMeZ9Cssi0VCSBG7v70MpwoPDHY13FaGA)

Try the latest version

**Comment by DarkAlchy** [comment]
Update through comfy manager?

**Comment by DarkAlchy** [comment]
Froze up.

WARNING SHAPE MISMATCH diffusion_model.label_emb.0.0.weight WEIGHT NOT MERGED torch.Size([1280, 2816]) != torch.Size([1280, 5632])

**Comment by kenic123** [comment]
我也是一样的报错，这是截图
![image](https://github.com/user-attachments/assets/db0b7d8d-7230-4f29-8fb8-d289db3eab71)

**Comment by wailovet** [comment]
> 我也是一样的报错，这是截图 ![image](https://private-user-images.githubusercontent.com/67681738/348518912-db0b7d8d-7230-4f29-8fb8-d289db3eab71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDA0ODIsIm5iZiI6MTcyMDk0MDE4MiwicGF0aCI6Ii82NzY4MTczOC8zNDg1MTg5MTItZGIwYjdkOGQtNzIzMC00ZjI5LThmYjgtZDI4OWRiM2VhYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA2NTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NmQ1MmQ0ZTE1MDczMTBlMTgwZjc4Yjk0YzRmYWY5NWNiN2I4YzIxZTJkYWQ4ZjU1MjQ4MDlhNWJkMGZiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6zHXI10dw5UdsmoAFdl0a_1tOmRegNT3Gwbelv17MU)

使用了哪个controlnet

**Comment by jinxishe** [comment]
更新到今天的版本后，我也出现了同样的错误。RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float，而前一个版本还是好的。

**Comment by wailovet** [comment]
> 更新到今天的版本后，我也出现了同样的错误。RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float，而前一个版本还是好的。

我还在尝试重现它,你们都是用的是f16的chatglm么

**Comment by jinxishe** [comment]
> > 更新到今天的版本后，我也出现了同样的错误。RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float，而前一个版本还是好的。
> 
> 我还在尝试重现它,你们都是用的是f16的chatglm么

是的，fp16 和 8 都尝试了，一样的错误信息。我的工作流仅是最简单的生成，没有使用 controlnet

**Comment by wailovet** [comment]
> > > 更新到今天的版本后，我也出现了同样的错误。RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float，而前一个版本还是好的。
> > 
> > 
> > 我还在尝试重现它,你们都是用的是f16的chatglm么
> 
> 是的，fp16 和 8 都尝试了，一样的错误信息。我的工作流仅是最简单的生成，没有使用 controlnet

能否微信联系下我

**Comment by jinxishe** [comment]
> > > > 更新到今天的版本后，我也出现了同样的错误。RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float，而前一个版本还是好的。
> > > 
> > > 
> > > 我还在尝试重现它,你们都是用的是f16的chatglm么
> > 
> > 
> > 是的，fp16 和 8 都尝试了，一样的错误信息。我的工作流仅是最简单的生成，没有使用 controlnet
> 
> 能否微信联系下我

要稍晚些时候，大约一个小时后可以。如何加你？

**Comment by wailovet** [comment]
> > > > > 更新到今天的版本后，我也出现了同样的错误。RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float，而前一个版本还是好的。
> > > > 
> > > > 
> > > > 我还在尝试重现它,你们都是用的是f16的chatglm么
> > > 
> > > 
> > > 是的，fp16 和 8 都尝试了，一样的错误信息。我的工作流仅是最简单的生成，没有使用 controlnet
> > 
> > 
> > 能否微信联系下我
> 
> 要稍晚些时候，大约一个小时后可以。如何加你？

minrszone
其他人有重现的也可以找下我协助定位下问题

**Comment by zackeryyy00** [comment]
使用chatglm3 fp16，遇到了同样的问题，除了chatglm3 外使用和示例完全相同的节点

**Comment by Chzzll** [comment]
我也是遇到同样的问题，在K采样器这里出错，使用的是最新版本的comfyui和插件

**Comment by jinxishe** [comment]
目前的最新代码在普通流程（无controlnet）下已经能正常运行。感谢作者的及时应对！

**Comment by Chzzll** [comment]
> 我也是遇到同样的问题，在K采样器这里出错，使用的漏洞的comfyui和插件
![1720943676305](https://github.com/user-attachments/assets/66cbcc23-d662-4062-ba69-41f0c6ddc41a)
![workflow](https://github.com/user-attachments/assets/33ca70e1-e76b-4c2a-ba07-76e0725b01c0)

**Comment by kenic123** [comment]
> > 我也是一样的报错，这是截图 ![image](https://private-user-images.githubusercontent.com/67681738/348518912-db0b7d8d-7230-4f29-8fb8-d289db3eab71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDA0ODIsIm5iZiI6MTcyMDk0MDE4MiwicGF0aCI6Ii82NzY4MTczOC8zNDg1MTg5MTItZGIwYjdkOGQtNzIzMC00ZjI5LThmYjgtZDI4OWRiM2VhYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA2NTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NmQ1MmQ0ZTE1MDczMTBlMTgwZjc4Yjk0YzRmYWY5NWNiN2I4YzIxZTJkYWQ4ZjU1MjQ4MDlhNWJkMGZiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6zHXI10dw5UdsmoAFdl0a_1tOmRegNT3Gwbelv17MU)
> 
> 使用了哪个controlnet

mistoline f16

**Comment by zackeryyy00** [comment]
更新代码后可以正常运行，大家可以尝试一下，感谢作者及时更新
